---
title: "Consular no Oriente Médio"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r, include = F, setup}
library(tidyverse)
library(readxl)

knitr::opts_chunk$set(echo = F, message = F, warning = F)

ano_2020 <- readxl::read_excel(here::here("data-raw/2020-2018producao_consular.xlsx"), sheet = 1, skip = 1) %>% 
  janitor::clean_names() %>% 
  mutate(across(3:last_col(), ~ .x %>% replace_na(0))) %>% 
  select(-c(1, 2)) %>% 
  mutate(posto = str_remove(posto, "^C ")) %>% 
  mutate(posto = str_remove(posto, "^CG ")) %>%
  mutate(posto = str_remove(posto, "^E ")) %>% 
  mutate(posto = str_remove(posto, "^VC ")) %>% 
  arrange(desc(posto)) %>% 
  rename(total = qtd_servi_a_os, total_ouro = tota_l_r_ouro) %>% 
  mutate(ano = "2020")

ano_2019 <- readxl::read_excel(here::here("data-raw/2020-2018producao_consular.xlsx"), sheet = 2, skip = 1) %>% 
  janitor::clean_names() %>% 
  mutate(across(3:last_col(), ~ .x %>% replace_na(0))) %>% 
  select(-c(1, 2)) %>% 
  mutate(posto = str_remove(posto, "^C ")) %>% 
  mutate(posto = str_remove(posto, "^CG ")) %>%
  mutate(posto = str_remove(posto, "^E ")) %>% 
  mutate(posto = str_remove(posto, "^VC ")) %>% 
  mutate(posto = str_trim(posto)) %>% 
  arrange(desc(posto)) %>% 
  select(-e_visa) %>% 
  rename(total = qtd_servicos, total_ouro = tota_l_r_ouro)%>% 
  mutate(ano = "2019")


ano_2018 <- readxl::read_excel(here::here("data-raw/2020-2018producao_consular.xlsx"), sheet = 3) %>% 
  janitor::clean_names() %>% 
  mutate(across(3:last_col(), ~ .x %>% replace_na(0))) %>% 
  select(-c(1)) %>% 
  mutate(postos = str_remove(postos, "^Consulado ")) %>% 
  mutate(postos = str_remove(postos, "^do Brasil em")) %>% 
  mutate(postos = str_remove(postos, "^Geral em")) %>% 
  mutate(postos = str_remove(postos, "^Consulado-Geral em")) %>% 
  mutate(postos = str_remove(postos, "^Consulado-Geral")) %>% 
  mutate(postos = str_remove(postos, "^Embaixada")) %>% 
  mutate(postos = str_remove(postos, "^Vice-Consulado ")) %>% 
  mutate(postos = str_remove(postos, "^em ")) %>% 
  mutate(postos = str_remove(postos, "^ em ")) %>% 
  mutate(postos = str_remove(postos, "^ na ")) %>% 
  mutate(postos = str_remove(postos, "^ no ")) %>% 
  mutate(postos = str_remove(postos, "^V\\.C\\. em ")) %>% 
  mutate(postos = str_trim(postos)) %>% 
  arrange(desc(postos)) %>% 
  select(-visto_eletronico) %>% 
  rename(total_ouro = emolumentos_totais_real_ouro, posto = postos) %>% 
  mutate(ano = "2018")


df <- ano_2020 %>% 
  dplyr::bind_rows(ano_2019) %>% 
  filter(posto != "0") %>% 
  filter(str_detect(posto, "CGAC", negate = T)) %>% 
  dplyr::bind_rows(ano_2018) %>%
  filter(str_detect(posto, "Total", negate = T)) %>% 
  filter(str_detect(posto, "TOTAL", negate = T))

paises_om <- c("Amã","Cairo","Beirute",
                 "Argel" ,"Rabat","Túnis",
                 "Abu Dhabi","Bagdá","Damasco",
                 "Doha","Kuaite","Mascate",
                 "Riade")

```

```{r total de documentos}

df %>% 
  filter(posto %in% paises_om) %>% 
  # arrange(desc(total))
  ggplot() +
  geom_col(aes(tidytext::reorder_within(posto, total, ano), total, fill = posto), position = "dodge",
           show.legend = F) +
  facet_wrap(~ ano, scales = "free_y") +
  coord_flip() +
  tidytext::scale_x_reordered() +
  labs(x = "Total de Documentos",
       y = NULL,
       title = "Postos no Oriente Médio, total de documentos") +
  ggthemes::scale_fill_tableau(palette = "Tableau 20") +
  theme_minimal()

```

```{r}

df %>% 
  filter(posto %in% paises_om | posto == "Pequim" | posto == "Luanda") %>% 
  mutate(passaporte = arb + pases + padip + pasof + pacom) %>% 
  arrange(desc(total)) %>% 
  select(-c(arb, pases, padip, pasof, pacom)) %>% 
  relocate(passaporte, .before = vistos) %>% 
  pivot_longer(2:6, names_to = "documento", values_to = "quantidade") %>% 
  ggplot() +
  geom_col(aes(quantidade, tidytext::reorder_within(posto, total, ano), fill = documento), position = "fill") +
  facet_wrap(~ ano, scales = "free") +
  theme_minimal() +
  ggthemes::scale_fill_tableau(name = "Documento", labels = c("Atos Notariais", "CPF", "Passaporte", "Registro Civil", "Vistos")) +
  tidytext::scale_y_reordered() +
  labs(title = "Proporção de documentos produzidos",
       subtitle = "Consulados no Oriente Médio",
       x = "Proporção", y = NULL)

```

```{r}
df %>% 
  filter(posto %in% paises_om) %>%
  filter(ano == "2020") %>% 
  ggplot() +
  geom_col(aes(reorder(posto, total), total, fill = total), position = "dodge",
           show.legend = F) +
  # facet_wrap(~ ano, scales = "free_y") +
  coord_flip() +
  # tidytext::scale_x_reordered() +
  labs(x = "Total de Documentos",
       y = NULL,
       title = "Postos no Oriente Médio, total de documentos") +
  # ggthemes::scale_fill_tableau(palette = "Tableau 20") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 4))
```




```{r vistos}

df %>% 
  filter(posto %in% paises_om) %>% 
  arrange(desc(vistos)) %>% 
  select(posto, vistos, ano) |> 
    ggplot() +
  geom_col(aes(tidytext::reorder_within(posto, vistos, ano), vistos, fill = posto), position = "dodge",
           show.legend = F) +
  facet_wrap(~ ano, scales = "free_y") +
  coord_flip() +
  tidytext::scale_x_reordered() +
  labs(x = "Total de Documentos",
       y = NULL,
       title = "Postos no Oriente Médio, total de vistos") +
  ggthemes::scale_fill_tableau(palette = "Tableau 20") +
  theme_minimal()



```

```{r}
df %>% 
  filter(posto %in% paises_om | posto == "Paris" | posto == "Londres") %>% 
  mutate(passaporte = arb + pases + padip + pasof + pacom) %>% 
  arrange(desc(passaporte)) %>% 
  select(ano, passaporte, posto) %>% 
  pivot_wider(names_from = ano, values_from = passaporte)
  ggplot() +
  geom_col(aes(tidytext::reorder_within(posto, passaporte, ano), passaporte, fill = posto), position = "dodge",
           show.legend = F) +
  facet_wrap(~ ano, scales = "free_y") +
  coord_flip() +
  tidytext::scale_x_reordered() +
  labs(x = "Total de Documentos",
       y = NULL,
       title = "Postos no Oriente Médio, total de vistos") +
  ggthemes::scale_fill_tableau(palette = "Tableau 20") +
  theme_minimal()
```

```{r}
df %>% 
  filter(posto == "Hamamatsu" | posto == "Nagoia" | posto == "Tóquio") %>%
  mutate(passaporte = arb + pases + padip + pasof + pacom) %>% 
  arrange(desc(passaporte)) %>% 
  select(ano, passaporte, posto) %>% 
  group_by(ano) %>% 
  summarise(soma = sum(passaporte))
  pivot_wider(names_from = ano, values_from = passaporte)
```

