library(tidyverse)

temas <- c("eleitoral",
  "presos",
  "nada",
  "outro",
  "casamento",
  "duvida e-consular",
  "carta escola",
  "procuração",
  "visto de negócios",
  "legalização",
  "visto de negócios",
  "duvida e-consular",
  "visto sirios",
  "carta escola",
  "legalização",
  "antecipação fila",
  "requisitos entrada egito",
  "casamento",
  "visto sírios",
  "duvida e-consular",
  "agendamento",
  "presos",
  "legalização",
  "requisitos para entrada no Brasil - covid",
  "presos",
  "duvida e-consular",
  "requisitos para entrada no Brasil - covid",
  "passaporte",
  "visto turismo",
  "agendamento e-consular",
  "requisitos para entrada no Brasil - outros",
  "presos",
  "casamento",
  "passaporte",
  "visto sírios",
  "visto de negócios",
  "registro de óbito",
  "visto para menores",
  "visto sírios",
  "visto turismo",
  "agendamento",
  "agendamento",
  "agendamento",
  "presos",
  "agendamento",
  "taxas consulares",
  "casamento",
  "assistência consular",
  "legalização",
  "legalização",
  "casamento",
  "visto turismo",
  "duvida e-consular",
  "legalização",
  "status pedido",
  "agendamento",
  "carta escola",
  "visto reuniao familiar",
  "visto reuniao familiar",
  "visto de negócios",
  "agendamento",
  "agendamento",
  "agendamento",
  "onde traduzir",
  "legalização",
  "visto de negócios",
  "certidao de nascimento",
  "outros",
  "visto transito",
  "agendamento",
  "casamento",
  "procuração",
  "passaporte",
  "casamento",
  "visto sírios",
  "casamento",
  "visto turismo")


temas %>% 
  as_tibble() %>% 
  group_by(value) %>% 
  count() %>% 
  arrange(desc(n))


casamento <- c("comunhão de bens",
               "registro",
               "registro",
               "registro",
               )

